### ISSUE TITLE
Allow dynamic branches in extra_plugin_runners

### ISSUE THREAD

**Issue by dmitriim** [catalyst/catalyst-moodle-workflows#110]
According to documentation you can use dynamic branches while using `moodle-plugin-ci add-plugin` like `moodle-plugin-ci add-plugin --branch $MOODLE_BRANCH username/project `see https://moodlehq.github.io/moodle-plugin-ci/AddExtraPlugins.html  

However I wasn't able get it working using catalyst-moodle-workflows. Either it's not supported or I just missed something. 

In any case would be nice to implement or/and document this feature.

**Comment by keevan** [comment]
Per the changes and example here #134 , the recommendation would be to add multiple jobs, and specify which branches and which remote dependencies you want to run it against.
