### ISSUE TITLE
Some Moodle versions showing the following Error:  Not enough arguments (missing: "plugin").  

### ISSUE THREAD

**Issue by luukverhoeven** [catalyst/catalyst-moodle-workflows#120]
I have a strange problem where the test says “Not enough arguments (missing: ‘plugin’).” But this isn’t the case for all releases. Is this a known problem?

See the following test results:
https://github.com/LdesignMedia/moodle-local_commander/actions/runs/10273057252/job/28426700810

![image](https://github.com/user-attachments/assets/8275c31c-b0ac-4441-bfd6-a269007968b7)

![image](https://github.com/user-attachments/assets/dc62bb61-c73b-4a2c-a970-74535b438bc5)

**Comment by matthewhilton** [comment]
Usually that is an indication the plugin install failed. Github automatically hides the dropdown though so its not super obvious, but if you click on the `Moodle install output` dropdown in the output, you'll see an error (probably https://github.com/catalyst/catalyst-moodle-workflows/issues/121)

**Comment by luukverhoeven** [comment]
@matthewhilton Thanks, I didn’t notice that error. It does seem related to https://github.com/moodlehq/moodle-plugin-ci/issues/309.

**Comment by matthewhilton** [comment]
Hey @luukverhoeven Moodle/NVM haven't been very quick to remediate this so i've just merged in a temporary downgrade of nvm to fix it temporarily.

If you try running your pipelines again they should work consistently now.

**Comment by luukverhoeven** [comment]
@matthewhilton Everything seems to be working again, thanks for the update. I’ll close this issue and hope Moodle/NVM resolves it correctly soon.
