### ISSUE TITLE
Downgrade node versions for MOODLE_400_STABLE and below

### ISSUE THREAD

**Issue by djarran** [catalyst/catalyst-moodle-workflows#129]
**Description:** Plugins started to experience issues due to incompatible node versions. This was fixed for MOODLE_401_STABLE (see #128) and above, but versions below are still experiencing errors as they must be lest than v17: 

`MOODLE_310_STABLE` - `MOODLE_400_STABLE`

```
  [info] Install npm dependencies
    ERR  npm WARN EBADENGINE Unsupported engine {
    ERR  npm WARN EBADENGINE   package: undefined,
    ERR  npm WARN EBADENGINE   required: { node: '>=16.14.0 <17' },
    ERR  npm WARN EBADENGINE   current: { node: 'v20.11.1', npm: '10.2.4' }
    ERR  npm WARN EBADENGINE }
    ERR  npm WARN EBADENGINE Unsupported engine {
    ERR  npm WARN EBADENGINE   package: '@es-joy/jsdoccomment@0.20.1',
    ERR  npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16 || ^17' },
    ERR  npm WARN EBADENGINE   current: { node: 'v20.11.1', npm: '10.2.4' }
    ERR  npm WARN EBADENGINE }
    ERR  npm WARN EBADENGINE Unsupported engine {
    ERR  npm WARN EBADENGINE   package: 'eslint-plugin-jsdoc@37.9.4',
    ERR  npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16 || ^17' },
    ERR  npm WARN EBADENGINE   current: { node: 'v20.11.1', npm: '10.2.4' }
    ERR  npm WARN EBADENGINE }
```

`MOODLE_39_STABLE`
```
  [info] Install npm dependencies
    ERR  npm WARN EBADENGINE Unsupported engine {
    ERR  npm WARN EBADENGINE   package: undefined,
    ERR  npm WARN EBADENGINE   required: { node: '>=16.14.0 <17' },
    ERR  npm WARN EBADENGINE   current: { node: 'v20.11.1', npm: '10.2.4' }
    ERR  npm WARN EBADENGINE }
```

Taken from the plugin CI execution: https://github.com/catalyst/moodle-assignsubmission_maharaws/actions/runs/11284526413/job/31385872515?pr=86

**Comment by danmarsden** [comment]
just adding a big +1 to drop support for testing against Moodle 3.9 and only support 4.1 and higher. but if someone "really" wants to fix this..... I suppose it doesn't hurt...

**Comment by brendanheywood** [comment]
I don't think catalyst-moodle-workflows itself should drop support for things in the general case, it should still work for out of support stuff. Individual plugins can and should declare what versions they support, and if they want to cut a new stable which supports new stables and drops old ones that is how it should be done. If we drop support in catalyst-moodle-workflows then it means that a plugin gets that decision forced upon them.
