### ISSUE TITLE
Using JS + AMD build, makes Catalyst CI give build errors

### ISSUE THREAD

**Issue by fulldecent** [catalyst/catalyst-moodle-workflows#137]
When attempting to add JS + AMD files into the repo, it produces build errors with Catalyst.

Here is one such run:

https://github.com/fulldecent/moodle-local_plugin_template/actions/runs/11916079633/job/33207931334

We are not sure if it is expected that we will include the built JS (which I think is the correct Moodle best practice).

**Comment by dmitriim** [comment]
Error: `File is stale and needs to be rebuilt: amd/build/canvas_confetti.min.js.map`
@fulldecent This means that version of node/dependencies you use locally are different to those used in Moodle version you run the test on. Please make sure you built your js in Moodle 4.5?

**Comment by dmitriim** [comment]
Alternatively you can use disable_grunt option to suppress this error. Usually handy when you support few version for your plugin and CI starts complaining about JS in the latest and you don't really want to rebuild js.

**Comment by marharyta-morozova** [comment]
> Error: `File is stale and needs to be rebuilt: amd/build/canvas_confetti.min.js.map` @fulldecent This means that version of node/dependencies you use locally are different to those used in Moodle version you run the test on. Please make sure you built your js in Moodle 4.5?

Hi, @dmitriim 

Yes, the JS build was on Moodle 4.5, with the Node.js and Grunt setup based on the Moodle [documentation](https://moodledev.io/general/development/tools/nodejs#install-nvm-and-node).

Additionally, to resolve the issue, the recommended approach from [here](https://github.com/moodlehq/moodle-plugin-ci/issues/319) was followed:

nvm install && nvm use && npm install from the Moodle root.

However, even after that, the CI issue remains unresolved.

**Comment by marharyta-morozova** [comment]
Already found this issue in [README](https://github.com/catalyst/catalyst-moodle-workflows/tree/bbb7b5fba5f8304b8b07ad5534b666202d1751c8?tab=readme-ov-file#amd--grunt-bundling-issues)
