### ISSUE TITLE
Secrets input field not handled correctly

### ISSUE THREAD

**Issue by keevan** [catalyst/catalyst-moodle-workflows#40]
The workflow is not valid. In .github/workflows/ci.yml (Line: 8, Col: 11): Error from called workflow catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main (Line: 35, Col: 9): Unexpected value 'default' catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main (Line: 181, Col: 9): Unrecognized named-value: 'secrets'. Located at position 107 within expression: needs.pre_job.outputs.should_skip != 'true' && needs.prepare_matrix.outputs.release_required == 'true' && secrets.MOODLE_ORG_TOKEN != ''

**Comment by jaypha** [comment]
For more context, this occurred here.
https://github.com/catalyst/moodle-tool_dataflows/actions/runs/2513227928
