### ISSUE TITLE
Add privacy tests to workflow

### ISSUE THREAD

**Issue by dmitriim** [catalyst/catalyst-moodle-workflows#5]
Or at least have something like: group-39-plus--with-privacy-ci.yml

Potential privacy steps:

```
      - name: Run phpunit
        if: ${{ always() }}
        run: |
          moodle-plugin-ci phpunit
          cd moodle
          vendor/bin/phpunit --fail-on-risky --disallow-test-output --group local_submissionrestict
          vendor/bin/phpunit --fail-on-risky --disallow-test-output --filter tool_dataprivacy_metadata_registry_testcase
          vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite core_privacy_testsuite --filter provider_testcase
```

**Comment by keevan** [comment]
I think the privacy check should just be part of the core workflow, and if we really wanted to, add an input to explicitly skip it.

**Comment by keevan** [comment]
As per https://github.com/catalyst/catalyst-moodle-workflows/blob/4d6d1f6/.github/plugin/setup/action.yml#L117-L118
 this has already been added previously by @Anupamatd :)

Closing ~
