### ISSUE TITLE
Fix phpdoc check

### ISSUE THREAD

**Issue by keevan** [catalyst/catalyst-moodle-workflows#64]
Currently it's not failing on errors, and also it is - in my humble opinion - painful to read. The suggested change here is to:
- [x] ensure the phpdoc actually returns an error when things aren't working. 
- [x] have an option to skip the phpdoc check if one doesn't already exist
- [x] preserve any expected functionality
- [x] trim the output to only show relevant files and errors
- [x] remove errors relating specifically to certain anonymous class usage - which I believe is actually a bug.

I have a modified version of this locally, which outputs only the things that need actioning, and removes certain things I do not deem to be unrecoverable errors. (e.g. using anonymous classes with a customised `__construct`.

It would be good to include those checks also into this CI.

**Comment by keevan** [comment]
Upstream logged issue:
https://github.com/moodlehq/moodle-local_moodlecheck/issues/91

**Comment by brendanheywood** [comment]
Rather than just trimming the output how about completely parsing it and turning into GitHub ci error syntax

::error file={name},line={line},endLine={endLine},title={title}::{message}

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message

the same can be said about all of the checks

**Comment by keevan** [comment]
Thanks for the link, that option does sounds interesting. The docs don't really provide a nice example showing what it would look like, but it would be great if the annotations appeared inline similar to performing a code review. Except it's not permanent in that if it's fixed, it simple ceases to exist.

I would probably split that into it's own issue though, and probably list it as a parent issue for all the different checks we want to convert it for.

The trimming is probably going to happen either way, and though it feels like it should be fixed upstream. The changes I had in mind are trivial and would continue to work even if upstream did _fix_ it.
