### ISSUE TITLE
Encourage github to run the master branch of the first run

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/catalyst-moodle-workflows#71]
This is because things like phpdocs only run on this branch and if it fails the faster we find out the better

**Comment by keevan** [comment]
Flipping the question a bit, would it be better if the order was from highest to lowest instead? (e.g. master, 400 311, 310, etc.)

**Comment by brendanheywood** [comment]
Yes totally agree. If we are on the verge of carving out a new stable branch its good to see it green down to the point we would split it
