### ISSUE TITLE
Reflect changes from https://github.com/badges/shields/issues/8671 in README

### ISSUE THREAD

**Issue by dmitriim** [catalyst/catalyst-moodle-workflows#83]
There were some breaking changes implemented so badge link in README needs to be updated. Please see https://github.com/badges/shields/issues/8671 for more info.

**Comment by keevan** [comment]
Thanks for reporting this @dmitriim

**Comment by keevan** [comment]
Also for those coming back, I've written a regex which could help perform the transformation needed, there are a few assumptions (e.g. workflow name matches file name and a branch is specified - recommended anyways)

https://regex101.com/r/IVH3Qh/4
