### ISSUE TITLE
Create and document guidelines for matrixs for long running branches

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/catalyst-moodle-workflows#9]
Ideas:

* lets say we have a 3.5-3.11 branch
* lets do a full matrix for each of 3.5 and 3.9 as they are LTS branches
* for other branches we could do just a single combination, and alternate things like which db we use
* make sure that the lowest and highest supported variants for each are tested, eg lowest node, highest node, earliest db, latest db
* if all of the above are satisfied, and we have 'spare' combinations, then we could just remove them for branches which are not an LTS and which are out of support but in between other stables which are tested. eg in this case some subset of 3.6 / 3.7 / 3.8 could be dropped completely

**Comment by keevan** [comment]
+1 to avoid problems like this :zany_face: (64 checks)

![image](https://user-images.githubusercontent.com/9924643/155270108-1fc1affa-2d1d-4310-b601-5ee17689d1f7.png)

Source: https://github.com/catalyst/moodle-tool_forcedcache/pull/42

**Comment by keevan** [comment]
This should be fixed and the ability to specify any tested branch is found at `.github/actions/matrix/matrix_includes.yml`.

This is the FULL list of inclusions, which is then filtered down per plugin - based on what it needs to run and check against.

If there are any further or less combinations required at a global scale, this will be the place to update it. 

The README will be updated with this information also.
